version: '3.8'

services:
  dev:
    container_name: shira-api-dev
    image: shira-api-dev:1.0.0
    build:
        context: .
        target: development
        dockerfile: ./Dockerfile.development
    command: yarn start:debug
    ports:
        - 3000:3000
        - 9229:9229
    networks:
        - nestjs-network
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: shira-api-prod
    image: shira-api-prod:1.0.0
    environment:
      JWT_SECRET: ${JWT_SECRET}  
    build:
        context: .
        target: production
        dockerfile: ./Dockerfile.production
    command: yarn start:prod
    ports:
        - 3000:3000
    networks:
        - nestjs-network
    restart: unless-stopped
  staging:
    container_name: shira-api-staging
    image: shira-api-staging:1.0.0
    environment:
      JWT_SECRET: ${JWT_SECRET}  
    build:
        context: .
        target: production
        dockerfile: ./Dockerfile.production
    command: yarn start:prod
    ports:
        - 3001:3000
    networks:
        - nestjs-network
    restart: unless-stopped
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"    
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nestjs-network

networks:
  nestjs-network:

volumes:
  db-data: